### ISSUE TITLE
Where to find the custom firmware?

### ISSUE THREAD

**Issue by WalaWala** [jeffmer/JeffsBangleAppsDev#1]
I'm trying to use my iPhone with the Bangle.js smart watch.
I came accross your repository and your post in the Bangle.js forums - but I can't find the modified Bangle.js firmware. Can you hint me in the right direction please?

**Comment by jeffmer** [comment]
It’s the zip file in the same directory as the widget:
[https://github.com/jeffmer/JeffsBangleAppsDev/tree/master/apps/widancsq](https://github.com/jeffmer/JeffsBangleAppsDev/tree/master/apps/widancsq)

**Comment by WalaWala** [comment]
Thanks. Just found it five minutes ago :)
I'm currently testing it. Some minor instability until now. I don't have currently that much time to fix it. Should I report it here?

**Comment by jeffmer** [comment]
Yes please, would be very interested in how you get on. When you want to connect the UART to the IDE etc it’s best to disable the widget in settings, then turn off the Bangle from settings, turn off Bluetooth in iPhone, then restart Bangle. The version in widancsq which requires the modified firmware is the most stable. I have given up on the other version. 
`It is worthwhile loading the ram widget as most problems are due to not having enough memory.

**Comment by WalaWala** [comment]
I think we can close this one then.
