### ISSUE TITLE
Button 1 and 3 freeze

### ISSUE THREAD

**Issue by WalaWala** [jeffmer/JeffsBangleAppsDev#3]
When the clock is displayed and button 1 or 3 is pressed the clock freezes.
(You did say that there was a kind of bug with those buttons if the modified widgets were not used, but I use the modified ones...)

**Comment by jeffmer** [comment]
Do you have all three of the clocks loaded? Buttons 1 & 3 switch between my three clocks. You may have to hack them if you do not want all three.

**Comment by WalaWala** [comment]
Ah I thought you needed all the widgets and not the clocks... After I've installed the clocks it seems to work better, thank your.

**Comment by jeffmer** [comment]
Actually, I have just fixed the clocks so that if BTN 1 or 2 is pressed and there is no corresponding clock app there is no crash. To get the new versions of the clocks, you need to delete all browsing data in Chrome and reload my app loader.
I have noticed that t when you enable the ANCS widget in Settings and then switch to the clock it does crash - working on it - however the simple fix is press button 3 until the clock reloads. It does not happen after that .
